name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  APP_NAME: OpenList-Desktop

jobs:
  # ====== Windows 构建 ======
  build-windows:
    runs-on: windows-latest
    env:
      WINDOWS_PORTABLE_NAME: OpenListDesktop_${{ github.ref_name }}_windows-x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          
      - name: Enable Windows desktop & Get dependencies
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
      
      - name: Build Windows application
        run: flutter build windows --release
      
      - name: Create portable ZIP
        run: |
          cd build/windows/x64/runner/Release
          7z a -tzip ${{ github.workspace }}/${{ env.WINDOWS_PORTABLE_NAME }}.zip ./*
        shell: cmd
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: ${{ github.workspace }}/${{ env.WINDOWS_PORTABLE_NAME }}.zip

  # ====== Linux 构建 ======
  build-linux:
    runs-on: ubuntu-latest
    env:
      LINUX_PORTABLE_NAME: OpenListDesktop_${{ github.ref_name }}_linux-x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      # =============== 安装核心依赖（失败将中断构建）==============
      - name: Install essential dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libgl1 \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libudev-dev
      # =============== 安装可选依赖（失败也不会中断）==============
      - name: Install optional dependencies (skip on failure)
        continue-on-error: true
        run: |
          sudo apt-get install -y libasound2t64 || echo "libasound2t64 skipped"
          sudo apt-get install -y libpulse-dev || echo "libpulse-dev skipped"
      # =============== 启用 Linux 桌面并获取依赖 ================
      - name: Enable Linux desktop & Get dependencies
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
      # =============== 构建 Linux 应用 ================
      - name: Build Linux application
        run: flutter build linux --release
      # =============== 打包构建产物 ================
      - name: Create portable tar.gz
        run: |
          cd build/linux/x64/release/bundle
          tar -czf ${{ github.workspace }}/${{ env.LINUX_PORTABLE_NAME }}.tar.gz ./*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-portable
          path: ${{ github.workspace }}/${{ env.LINUX_PORTABLE_NAME }}.tar.gz
