name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  APP_NAME: OpenList-Desktop

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      WINDOWS_PORTABLE_NAME: OpenListDesktop_${{ github.ref_name }}_windows-x86_64

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          
      - name: Install dependencies
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
      
      - name: Build Windows application
        run: flutter build windows --release
      
      - name: Create portable ZIP
        run: |
          cd build/windows/x64/runner/Release
          7z a -tzip ${{ github.workspace }}/${{ env.WINDOWS_PORTABLE_NAME }}.zip ./*
        shell: cmd
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: ${{ github.workspace }}/${{ env.WINDOWS_PORTABLE_NAME }}.zip